version: "3.8"

services:
  recipe_scaler_db:
    container_name: recipe_scaler_db
    hostname: recipe_scaler_db
    image: postgres:15.2
    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRES_ADMIN_USERNAME: recipe_scaler_admin
      POSTGRES_PASSWORD: andreaadrienlindsay
    volumes: [pgdata:/var/lib/postgresql/data]
  frontend_server:
    container_name: frontend_server
    hostname: frontend_server
    image: docker-react-i
    build: 
      context: .
    ports: 
      - 3000:80


volumes:
  pgdata:
