services:
 
  recipe_scaler_db:
    container_name: recipe_scaler_db
    hostname: recipe_scaler_db
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_ADMIN_USERNAME: recipe_scaler_admin
      POSTGRES_PASSWORD: andreaadrienlindsay
    volumes: pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
