version: "3.8"

services:
  recipe_scaler_db:
    container_name: recipe_scaler_db
    hostname: recipe_scaler_db
    image: postgres:15.2
    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRES_ADMIN_USERNAME: recipe_scaler_admin
      POSTGRES_PASSWORD: andreaadrienlindsay
    volumes: 
      - pgdata:/var/lib/postgresql/data
  react-ui:
    container_name: react-ui
    hostname: react-ui
    image: node:18
    restart: always
    build:
      context: ./front-end-react
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./front-end-react:/front-end-react
      - /front-end-react/node_modules
    # command: /front-end-react/entrypoint.sh


volumes:
  pgdata:
